Ensure tokens revoked from Cognito aren't used to interact with Fractl
fractl-io/fractl pull request #1169
Opened 2023-11-21 11:46 UTC by pratik-fractl

Keep track of UserSessions and safe guard against Users who have logged out from Design Studio yet, use the JWT token via HTTP requests.

2023-11-21 15:17 UTC, pratik-fractl commented on src/fractl/http.clj
> +      (when-not (and (buddy/authenticated? request) (= logged-in-status true))
Acutally, `buddy/authenticated?` doesn't decode the jwt. It just checks for `:identity` key present in the request.

2023-11-21 15:17 UTC, pratik-fractl commented on src/fractl/http.clj
> +        logged-in-status (get
Will do.

2023-11-22 07:06 UTC, vijayfractl requested changes

2023-11-22 07:06 UTC, vijayfractl commented on src/fractl/http.clj
> +              (if
Please move the session event evaluations to a separate fn and reuse that here and at line 801.

2023-11-22 07:06 UTC, vijayfractl commented on src/fractl/http.clj
> +      (when-not (and (buddy/authenticated? request) (= logged-in-status true))
even then `(= logged-in-status true)` is cheaper.

2023-11-22 07:17 UTC, vijayfractl requested changes

2023-11-22 08:38 UTC, vijayfractl approved these changes

2023-11-22 09:37 UTC, merged