Unit tests to verify client side error messages
fractl-io/fractl pull request #1180
Opened 2023-11-25 01:32 UTC by hasnainnaeem

2023-11-27 03:59 UTC, vijayfractl requested changes

2023-11-27 03:59 UTC, vijayfractl commented on test/fractl/test/util/errors.cljc
> +(ns fractl.test.util.errors
Please move this to test/fractl/test.

2023-11-27 13:43 UTC, muazzam0x48 submitted a review, later dismissed

2023-11-27 13:46 UTC, muazzam0x48 approved these changes

2023-11-28 03:27 UTC, vijayfractl approved these changes

2023-11-28 04:28 UTC, merged