`get-user` endpoint should return ID of associated `:User` entity instance
fractl-io/fractl pull request #1187
Opened 2023-11-30 09:41 UTC by pratik-fractl

Changes:

* Store AppId user in auth backend
* `get-user` endpoint also returns :AppId

2023-12-01 06:03 UTC, vijayfractl requested changes

2023-12-01 06:12 UTC, vijayfractl submitted a review, later dismissed

2023-12-04 17:27 UTC, fractlrao submitted a review, later dismissed

2023-12-05 10:31 UTC, pratik-fractl commented on src/fractl/auth/cognito.clj
> +                :user-attributes [["custom:app_id" AppId]]))
Yes, it can update 3 things as per the investigation on what we receive request for req-type as `:User` to update it, it's  `FirstName` `LastName` `Email``AppId`. I'll add support to update here.

But, for having only one `admin-update-user-attributes`, the nature is different for just `:User` request and `UpdateUser` request, for User request we receive `:UserDetails` as `nil` and we don't receive cognito-username. That's why there is a call to query a given email to receive it's username to update it. So, the different type of call on different `if` cases,

2023-12-05 10:42 UTC, vijayfractl approved these changes

2023-12-05 10:50 UTC, merged