GraphQL schema generation and query resolver code
fractl-io/fractl pull request #1284
Opened 2024-04-05 05:49 UTC by hasnainnaeem

Work under progress. Remaining:
- Authentication/middleware 
- Coverage for more scenarios + test cases

2024-04-05 05:57 UTC, hasnainnaeem commented on src/fractl/graphql/resolvers.clj
> +(defn get-app-components []
This will be factored out from here. Component name from resolver-map will flow to wherever it's being called.

2024-04-05 06:02 UTC, hasnainnaeem commented on src/fractl/graphql/resolvers.clj
> +(defn- find-schema [fetch-names find-schema]
This will be factored out from here. Info from resolver-map will flow to wherever it's being called.

2024-04-05 09:51 UTC, vijayfractl requested changes

2024-04-05 09:51 UTC, vijayfractl commented on src/fractl/core.clj
> +(def internal-component-names
Instead of maintaining a static list like this, call:

```
(:components (cn/fetch-model :Fractl))
```

Also please move the whole logic of cleaning-up component names to `fractl.component` and access it via a call like `(cn/external-component-names)` or something like that.

2024-04-05 09:51 UTC, vijayfractl commented on src/fractl/core.clj
> +      (do
This `(do ...)` block is not needed as the following `(let ...)` introduces the necessary block structure.

2024-04-05 09:51 UTC, vijayfractl commented on src/fractl/core.clj
> +        (println "Finished processing compiled model."))
Do not leave `println` statements in final code, please use `log/info` or `log/debug` to log relevant details.

2024-04-05 09:51 UTC, vijayfractl commented on src/fractl/graphql/generator.clj
> +(def entities-code (atom {}))
These atoms seems to be updated for each invocation of the API - to keep track of each invocation specific information. This will cause in a multi-threaded environment. While this may be OK in a command-line mode, if we expose the graphql conversion over an API, the code will have data-race issues. Please update the code to use a more functional style (no session-specific mutable-data). 

If you need to maintain some global mutable-state, please consider using the `cell` abstraction in `fractl.util`.

2024-04-18 11:24 UTC, hasnainnaeem commented on src/fractl/graphql/generator.clj
> +(def entities-code (atom {}))
Good catch! Schema generation was supposed to happen only once, I have fixed it. Thanks

2024-04-22 04:53 UTC, vijayfractl approved these changes

2024-04-22 05:15 UTC, merged