Graphql mutation enhancements
fractl-io/fractl pull request #1308
Opened 2024-04-24 22:26 UTC by hasnainnaeem

2024-04-25 04:31 UTC, vijayfractl requested changes

2024-04-25 04:31 UTC, vijayfractl commented on src/fractl/graphql/resolvers.clj
> +            results (first (eval-patterns core-component update-pattern context))]
there's no need for declaring `results`

2024-04-25 04:31 UTC, vijayfractl commented on src/fractl/graphql/resolvers.clj
> +          results (eval-patterns core-component delete-pattern context)]
there's no need for declaring `results`

2024-04-25 04:31 UTC, vijayfractl commented on src/fractl/graphql/resolvers.clj
> +        results-with-parent-id))))
no need to declare `results-with-parent-id`

2024-04-25 04:31 UTC, vijayfractl commented on src/fractl/graphql/resolvers.clj
> +            results-with-parent-id (if (and (seq results) (map? (first results))) ;; map isn't returned when no records are deleted
this could be a `when`

2024-04-25 04:31 UTC, vijayfractl commented on src/fractl/graphql/resolvers.clj
> +          results (eval-patterns core-component create-pattern context)]
no need to bind return value to a var

2024-04-25 04:32 UTC, vijayfractl commented
@hasnainnaeem also make sure the test pass

2024-04-29 22:48 UTC, hasnainnaeem commented on src/fractl/graphql/resolvers.clj
> +          results (if dataflow-result
That'll throw an error because Lacinia expects a vector.

2024-04-29 22:54 UTC, hasnainnaeem commented on src/fractl/graphql/resolvers.clj
> +            results-with-parent-id (if (and (seq results) (map? (first results))) ;; map isn't returned when no records are deleted
Else block is also needed here

2024-05-13 04:22 UTC, vijayfractl approved these changes

2024-05-13 04:28 UTC, merged