added nrepl support
fractl-io/fractl pull request #1322
Opened 2024-05-08 10:28 UTC by hasnainnaeem

2024-05-08 10:29 UTC, hasnainnaeem commented on src/fractl/component.cljc
> -         :tag typtag}))
@vijayfractl could you please look into this? I have added the context here.

2024-05-08 10:31 UTC, hasnainnaeem commented on src/fractl/core.clj
>              [fractl.util.seq :as su]
Several have been moved to the utility class - this was needed to prevent cyclic dependencies.

2024-05-08 10:32 UTC, hasnainnaeem commented on src/fractl/core.clj
>      (println "Please enter a description of the app after the -i option.")))
We're using all nREPL middleware and simply replacing eval middleware.

2024-05-09 05:03 UTC, vijayfractl commented on src/fractl/lang/tools/nrepl/middleware/interruptible_eval.clj
> +           :eval (let [eval-fn (deref nrepl-eval-init)]
For clarity, each case-consequent could be moved to a separate function.

2024-05-09 05:08 UTC, vijayfractl requested changes

2024-05-09 05:08 UTC, vijayfractl commented on src/fractl/util/core.clj
> +(ns fractl.util.core
This looks like some refactoring+code to initialize nrepl. Please move the nrepl-initialization to a `ns` like `fractl.lang.tools.nrepl` and save the refactoring for another PR.

2024-05-09 06:18 UTC, vijayfractl commented on src/fractl/component.cljc
> +     ;(when-not (and (component-exists? component))
@hasnainnaeem I uncommented this code and ran fractl nrepl - not able to reproduce this error.

2024-05-09 06:20 UTC, vijayfractl approved these changes

2024-05-09 07:23 UTC, vijayfractl approved these changes

2024-05-09 07:45 UTC, pratik-fractl approved these changes

2024-05-09 07:45 UTC, merged