Integrate inference implementation with calling Inference-service
fractl-io/fractl pull request #1389
Opened 2024-06-12 13:38 UTC by kumarshantanu

This PR makes changes to `inference` implementation to call inference-service.

2024-06-13 16:57 UTC, pratik-fractl requested changes

2024-06-13 16:57 UTC, pratik-fractl commented on project.clj
> +(defproject com.github.fractl-io/fractl "0.5.3-SNAPSHOT"
Wrong version name, we don't use `SNAPSHOT` here. Let's just use `0.5.3`.

2024-06-28 06:38 UTC, kumarshantanu commented on project.clj
> +(defproject com.github.fractl-io/fractl "0.5.3-SNAPSHOT"
Discussed with @vijayfractl - he is OK with `-SNAPSHOT`. @pratik-fractl Anything that might break due to `-SNAPSHOT`?

2024-06-28 06:50 UTC, pratik-fractl approved these changes

2024-06-28 06:57 UTC, merged